// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.3
// source: odin/odin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateInstanceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreateInstanceReq) Reset() {
	*x = CreateInstanceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odin_odin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateInstanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceReq) ProtoMessage() {}

func (x *CreateInstanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_odin_odin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceReq.ProtoReflect.Descriptor instead.
func (*CreateInstanceReq) Descriptor() ([]byte, []int) {
	return file_odin_odin_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInstanceReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateInstanceRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *CreateInstanceRsp) Reset() {
	*x = CreateInstanceRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_odin_odin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateInstanceRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceRsp) ProtoMessage() {}

func (x *CreateInstanceRsp) ProtoReflect() protoreflect.Message {
	mi := &file_odin_odin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceRsp.ProtoReflect.Descriptor instead.
func (*CreateInstanceRsp) Descriptor() ([]byte, []int) {
	return file_odin_odin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInstanceRsp) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_odin_odin_proto protoreflect.FileDescriptor

var file_odin_odin_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6f, 0x64, 0x69, 0x6e, 0x2f, 0x6f, 0x64, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x27, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x11, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x32, 0x43, 0x0a, 0x08, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x37, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74,
	0x12, 0x12, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x73, 0x70, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x6f, 0x64,
	0x69, 0x6e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_odin_odin_proto_rawDescOnce sync.Once
	file_odin_odin_proto_rawDescData = file_odin_odin_proto_rawDesc
)

func file_odin_odin_proto_rawDescGZIP() []byte {
	file_odin_odin_proto_rawDescOnce.Do(func() {
		file_odin_odin_proto_rawDescData = protoimpl.X.CompressGZIP(file_odin_odin_proto_rawDescData)
	})
	return file_odin_odin_proto_rawDescData
}

var file_odin_odin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_odin_odin_proto_goTypes = []interface{}{
	(*CreateInstanceReq)(nil), // 0: CreateInstanceReq
	(*CreateInstanceRsp)(nil), // 1: CreateInstanceRsp
}
var file_odin_odin_proto_depIdxs = []int32{
	0, // 0: Instance.CreateStudent:input_type -> CreateInstanceReq
	1, // 1: Instance.CreateStudent:output_type -> CreateInstanceRsp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_odin_odin_proto_init() }
func file_odin_odin_proto_init() {
	if File_odin_odin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_odin_odin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateInstanceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_odin_odin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateInstanceRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_odin_odin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_odin_odin_proto_goTypes,
		DependencyIndexes: file_odin_odin_proto_depIdxs,
		MessageInfos:      file_odin_odin_proto_msgTypes,
	}.Build()
	File_odin_odin_proto = out.File
	file_odin_odin_proto_rawDesc = nil
	file_odin_odin_proto_goTypes = nil
	file_odin_odin_proto_depIdxs = nil
}
